#Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true

#Kotlin
kotlin.code.style=official
# https://youtrack.jetbrains.com/issue/KT-78504
kotlin.js.yarn=false

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
# Disable buildFeatures flags by default
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false


# Maven Central
GROUP=io.github.darkokoa
POM_ARTIFACT_ID=datetime-wheel-picker
VERSION_NAME=1.4.0

POM_NAME=DateTime Wheel Picker
POM_INCEPTION_YEAR=2024
POM_DESCRIPTION=Wheel Date & Time Picker in Compose Multiplatform
POM_URL=https://github.com/darkokoa/compose-datetime-wheel-picker

POM_SCM_URL=https://github.com/darkokoa/compose-datetime-wheel-picker
POM_SCM_CONNECTION=scm:git:git://github.com/darkokoa/compose-datetime-wheel-picker.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:darkokoa/compose-datetime-wheel-picker.git

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=darkokoa
POM_DEVELOPER_NAME=darkokoa
POM_DEVELOPER_URL=https://github.com/darkokoa/
